name: CI build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: oven-sh/setup-bun@v2
    - run: |
        cd .\frontend
        bun install
        bun run build
    - run: |
        pip install uv
        uv sync
        .\package_all.bat
#        pip install pywebview
#        pyinstaller --noconfirm --onefile --console --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/" --additional-hooks-dir=".\\hooks" "./ui_webview.py" --name "NsEmuTools-webview"
    - uses: actions/upload-artifact@v4
      with:
        path: dist/NsEmuTools.exe
        name: NsEmuTools
    - uses: actions/upload-artifact@v4
      with:
        path: dist/NsEmuTools-console.exe
        name: NsEmuTools-console
    - uses: actions/upload-artifact@v4
      with:
        path: dist/NsEmuTools
        name: NsEmuTools-dir
    - name: Release
      uses: softprops/action-gh-release@v2.2.2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        draft: true
        files: |
          dist/*.exe
          dist/*.7z
