name: Manual build console

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest']

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - uses: oven-sh/setup-bun@v2
    - run: |
        cd .\frontend
        bun install
        bun run build
    - run: |
        pip install uv
        uv sync
        uv run pyinstaller --noconfirm --onefile --console --icon "./web/favicon.ico" --add-data "./module/*.exe;./module/" --add-data "./web;web/"  "./main.py" --additional-hooks-dir=".\\hooks" --name "NsEmuTools-console"
    - uses: actions/upload-artifact@v4
      with:
        path: dist/*
        name: NsEmuTools-console
